project:
  type: book
  output-dir: docs

book:
  title: "스터디: Python for Data Analysis 3E"
  author: "방태모"
  date: 2023-04-01
  chapters:
    - index.qmd
    - chapter2.qmd
    - chapter3.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

lang: kr